<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>s</string>
		<string>z80</string>
		<string>$C</string>
	</array>
	<key>name</key>
	<string>Z80 Assembly</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(DEFM|DEFB|DEFS|DEFW|ORG|EQU|ENT|DISP|M|P|PE|PO|defm|defb|defs|defw|org|equ|ent|disp|m|p|pe|po|DB|db|DW|dw)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(Z|NZ|C|NC|z|nz|c|nc)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.asm.z80</string>
				</dict>
			</dict>
			<key>end</key>
			<string>"</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.asm.z80</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.double.include.asm.z80</string>
		</dict>
		<dict>
			<key>match</key>			
			<string>\b(ADC|ADD|AND|BIT|CALL|CCF|CP|CPD|CPDR|CPI|CPIR|CPL|DAA|DEC|DI|DJNZ|EI|EX|EXX|HALT|IM|IN|INC|IND|INDR|INI|INIR|JP|JR|LD|LDD|LDDR|LDI|LDIR|M|NC|NEG|NOP|NV|NZ|OR|OTDR|OTIR|OUT|OUTD|OUTI|POP|PUSH|RES|RET|RETI|RETN|RL|RLA|RLC|RLCA|RLD|RR|RRA|RRC|RRCA|RRD|RST|SBC|SCF|SET|SLA|SWAP|SRA|SRL|SUB|XOR|adc|add|and|bit|call|ccf|cp|cpd|cpdr|cpi|cpir|cpl|daa|dec|di|djnz|ei|ex|exx|halt|im|in|inc|ind|indr|ini|inir|jp|jr|ld|ldd|lddr|ldi|ldir|m|nc|neg|nop|nv|nz|or|otdr|otir|out|outd|outi|pop|push|res|ret|reti|retn|rl|rla|rlc|rlca|rld|rr|rra|rrc|rrca|rrd|rst|sbc|scf|set|sla|swap|sra|srl|sub|xor|LDA|lda)\b</string>
			<key>name</key>
			<string>keyword.mnemonic.asm.z80</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\d{5}</string>
			<key>name</key>
			<string>invalid</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b-?[0-9]+\b</string>
			<key>name</key>
			<string>constant.numeric.dec</string>
		</dict>
		<dict>
			<key>match</key>
			<string>[#$%]-?(0x)?[0-9a-fA-F]+\b</string>
			<key>name</key>
			<string>constant.numeric.hex</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b(A|B|C|D|E|F|H|L|I|R|IX|IY|AF|BC|DE|HL|PC|SP|AF'|Z|a|b|c|d|e|f|h|l|i|r|ix|iy|af|bc|de|hl|pc|sp|af'|z|HLI|hli|HLD|hld)\b</string>
			<key>name</key>
			<string>support.type.asm</string>
		</dict>		
	</array>
	<key>scopeName</key>
	<string>source.asm.z80</string>
	<key>uuid</key>
	<string>5075ff92-54a7-11e6-beb8-9e71128cae77</string>
</dict>
</plist>
